In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

C:\Users\hp\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\hp\anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\hp\anaconda3\lib\site-packages\numpy\.libs\libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:\n%s" %


# Variable	Description
# Loan_ID	Unique Loan ID
# Gender	Male/ Female
# #Dependents	Number of dependents
# Education	Applicant Education (Graduate/ Under Graduate)
# ApplicantIncome	Applicant income
# CoapplicantIncome	Coapplicant income
# Loan_Amount_Term	Term of loan in months
# Credit_History	credit history meets guidelines
# Property_Area	Urban/ Semi Urban/ Rural

In [349]:
df = pd.read_csv(r'train_ctrUa4K.csv')

In [350]:
df

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [351]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

# handle null values

In [352]:
#gender

In [353]:
df['Gender'].mode()

0    Male
dtype: object

In [354]:
df['Gender'] = df['Gender'].fillna('Male')

In [355]:
#married

In [356]:
df['Married'].mode()

0    Yes
dtype: object

In [357]:
df['Married'] = df['Married'].fillna('Yes')

In [358]:
#Dependent

In [359]:
df['Dependents'].unique()

array(['0', '1', '2', '3+', nan], dtype=object)

In [360]:
df['Dependents'].mode()

0    0
dtype: object

In [361]:
df['Dependents'] = df['Dependents'].fillna('0')

In [362]:
#Self_Employed

In [363]:
df['Self_Employed'].mode()

0    No
dtype: object

In [364]:
df['Self_Employed'] = df['Self_Employed'].fillna('No')

In [365]:
#fill tha null value using mean
#LoanAmount

In [366]:
df['LoanAmount'].mean()

146.41216216216216

In [367]:
df['LoanAmount'] = df['LoanAmount'].fillna('146.4')

In [368]:
df['Loan_Amount_Term'].mean()

342.0

In [369]:
df['Loan_Amount_Term'] = df['Loan_Amount_Term'].fillna(342.0)

In [370]:
#Credit_History 

In [371]:
df['Credit_History'].mode()

0    1.0
dtype: float64

In [372]:
df['Credit_History'].unique()

array([ 1.,  0., nan])

In [373]:
df['Credit_History'] = df['Credit_History'].fillna('1.0')

In [374]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [375]:
df.corr()

ApplicantIncome  CoapplicantIncome  Loan_Amount_Term
ApplicantIncome           1.000000          -0.116605         -0.045242
CoapplicantIncome        -0.116605           1.000000         -0.059675
Loan_Amount_Term         -0.045242          -0.059675          1.000000

In [376]:
#preprocessing

In [377]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             614 non-null    object 
 2   Married            614 non-null    object 
 3   Dependents         614 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      614 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    object 
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    object 
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(2), int64(1), object(10)
memory usage: 62.5+ KB


In [378]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

In [379]:
label = LabelEncoder()

In [380]:
one = OneHotEncoder()

In [381]:
df['Loan_ID'] = label.fit_transform(df['Loan_ID'])

In [382]:
df['Gender']= label.fit_transform(df['Gender'])

In [383]:
df['Married'] = label.fit_transform(df['Married'])

In [384]:
df['Education'] = label.fit_transform(df['Education'])

In [385]:
df['Self_Employed'] = label.fit_transform(df['Self_Employed'])

In [386]:
df['Property_Area'] = label.fit_transform(df['Property_Area'])

In [387]:
df['Loan_Status'] = label.fit_transform(df['Loan_Status'])

In [388]:
df['Dependents'].unique()

array(['0', '1', '2', '3+'], dtype=object)

In [389]:
df['Dependents'] = label.fit_transform(df['Dependents'])

In [390]:
df

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0          0       1        0           0          0              0   
1          1       1        1           1          0              0   
2          2       1        1           0          0              1   
3          3       1        1           0          1              0   
4          4       1        0           0          0              0   
..       ...     ...      ...         ...        ...            ...   
609      609       0        0           0          0              0   
610      610       1        1           3          0              0   
611      611       1        1           1          0              0   
612      612       1        1           2          0              0   
613      613       0        0           0          0              1   

     ApplicantIncome  CoapplicantIncome LoanAmount  Loan_Amount_Term  \
0               5849                0.0      146.4             360.0   
1               4583             1508.0      128.0             360.0   
2               3000                0.0       66.0             360.0   
3               2583             2358.0      120.0             360.0   
4               6000                0.0      141.0             360.0   
..               ...                ...        ...               ...   
609             2900                0.0       71.0             360.0   
610             4106                0.0       40.0             180.0   
611             8072              240.0      253.0             360.0   
612             7583                0.0      187.0             360.0   
613             4583                0.0      133.0             360.0   

    Credit_History  Property_Area  Loan_Status  
0              1.0              2            1  
1              1.0              0            0  
2              1.0              2            1  
3              1.0              2            1  
4              1.0              2            1  
..             ...            ...          ...  
609            1.0              0            1  
610            1.0              0            1  
611            1.0              2            1  
612            1.0              2            1  
613            0.0              1            0  

[614 rows x 13 columns]

In [391]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    int32  
 1   Gender             614 non-null    int32  
 2   Married            614 non-null    int32  
 3   Dependents         614 non-null    int32  
 4   Education          614 non-null    int32  
 5   Self_Employed      614 non-null    int32  
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    object 
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    object 
 11  Property_Area      614 non-null    int32  
 12  Loan_Status        614 non-null    int32  
dtypes: float64(2), int32(8), int64(1), object(2)
memory usage: 43.3+ KB


In [392]:
df['LoanAmount'] = df['LoanAmount'].astype(float)

In [393]:
df['Credit_History'] = df['Credit_History'].astype(float)

In [394]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    int32  
 1   Gender             614 non-null    int32  
 2   Married            614 non-null    int32  
 3   Dependents         614 non-null    int32  
 4   Education          614 non-null    int32  
 5   Self_Employed      614 non-null    int32  
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    int32  
 12  Loan_Status        614 non-null    int32  
dtypes: float64(4), int32(8), int64(1)
memory usage: 43.3 KB


In [395]:
#build model 

In [396]:
x = df.iloc[:,:-1]

In [397]:
x

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0          0       1        0           0          0              0   
1          1       1        1           1          0              0   
2          2       1        1           0          0              1   
3          3       1        1           0          1              0   
4          4       1        0           0          0              0   
..       ...     ...      ...         ...        ...            ...   
609      609       0        0           0          0              0   
610      610       1        1           3          0              0   
611      611       1        1           1          0              0   
612      612       1        1           2          0              0   
613      613       0        0           0          0              1   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0       146.4             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History  Property_Area  
0               1.0              2  
1               1.0              0  
2               1.0              2  
3               1.0              2  
4               1.0              2  
..              ...            ...  
609             1.0              0  
610             1.0              0  
611             1.0              2  
612             1.0              2  
613             0.0              1  

[614 rows x 12 columns]

In [398]:
y = df.iloc[:,-1]

In [399]:
y

0      1
1      0
2      1
3      1
4      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 614, dtype: int32

In [400]:
from sklearn.model_selection import train_test_split

In [401]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier 
from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier,GradientBoostingClassifier

In [402]:
Lo = LogisticRegression()

In [403]:
tree = DecisionTreeClassifier()

In [404]:
rand = RandomForestClassifier()

In [405]:
ada = AdaBoostClassifier()

In [406]:
grad = GradientBoostingClassifier()

In [407]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.20)

In [408]:
Lo.fit(xtrain,ytrain)

C:\Users\hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [409]:
tree.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [410]:
rand.fit(xtrain,ytrain)

RandomForestClassifier()

In [411]:
ada.fit(xtrain,ytrain)

AdaBoostClassifier()

In [412]:
grad.fit(xtrain,ytrain)

GradientBoostingClassifier()

In [413]:
#score all models

In [414]:
from sklearn.metrics import confusion_matrix,roc_auc_score

In [415]:
lo1 = Lo.predict(xtest)

In [417]:
print('train score Logistic regression',Lo.score(xtrain,ytrain))
print('test score logistic regression',Lo.score(xtest,ytest))
print('roc_auc_score',roc_auc_score(lo1,ytest))
print(confusion_matrix(lo1,ytest))


train score Logistic regression 0.8085539714867617
test score logistic regression 0.8211382113821138
roc_auc_score 0.8727226720647774
[[18  1]
 [21 83]]


In [418]:
tree1 = tree.predict(xtest)

In [419]:
print('train score Desicion tree',tree.score(xtrain,ytrain))
print('test score Desicion tree',tree.score(xtest,ytest))
print('roc_auc_score',roc_auc_score(tree1,ytest))
print(confusion_matrix(tree1,ytest))

train score Desicion tree 1.0
test score Desicion tree 0.8048780487804879
roc_auc_score 0.7803030303030304
[[24  9]
 [15 75]]


In [420]:
rand1 = rand.predict(xtest)

In [421]:
print('train score random forest',rand.score(xtrain,ytrain))
print('test score random forest',rand.score(xtest,ytest))
print('roc_auc_score',roc_auc_score(rand1,ytest))
print(confusion_matrix(rand1,ytest))

train score random forest 1.0
test score random forest 0.8048780487804879
roc_auc_score 0.8130434782608696
[[19  4]
 [20 80]]


In [422]:
ada1 = ada.predict(xtest)

In [423]:
print('train score adaboost',ada.score(xtrain,ytrain))
print('test score adaboost',ada.score(xtest,ytest))
print('roc_auc_score',roc_auc_score(ada1,ytest))
print(confusion_matrix(ada1,ytest))

train score adaboost 0.845213849287169
test score adaboost 0.7560975609756098
roc_auc_score 0.7277551020408163
[[17  8]
 [22 76]]


In [424]:
grad1 = grad.predict(xtest)

In [425]:
print('train score gradientboost',grad.score(xtrain,ytrain))
print('test score gradientboost',grad.score(xtest,ytest))
print('roc_auc_score',roc_auc_score(grad1,ytest))
print(confusion_matrix(grad1,ytest))

train score gradientboost 0.8940936863543788
test score gradientboost 0.8211382113821138
roc_auc_score 0.8397826086956521
[[20  3]
 [19 81]]


In [426]:
#this model manly facuse less then  type 2 error ,why type 2 error acually  is nagative predict positive approvel loan nagative parson 
#loan loss my meny.

# handle imblance data

In [430]:
df['Loan_Status'].value_counts()

1    422
0    192
Name: Loan_Status, dtype: int64

In [434]:
count1,count0 = df['Loan_Status'].value_counts()

In [435]:
count0

192

In [436]:
count1

422

In [438]:
sampl1 = df[(df['Loan_Status'] == 1)]

In [439]:
sampl0 = df[(df['Loan_Status'] == 0)]

In [443]:
loan0 = sampl0.sample(count1,replace = True)

In [445]:
df1 = pd.concat([sampl1,loan0],axis=0)

In [455]:
x1 = df1.iloc[:,:-1]

In [456]:
y1 = df1.iloc[:,-1]

In [457]:
y1.value_counts()

0    422
1    422
Name: Loan_Status, dtype: int64

In [458]:
x1train,x1test,y1train,y1test = train_test_split(x1,y1,test_size = 0.20)

In [459]:
Lo.fit(x1train,y1train)

C:\Users\hp\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [460]:
lopred = Lo.predict(x1test)

In [461]:
print('train score Logistic regression',Lo.score(x1train,y1train))
print('test score logistic regression',Lo.score(x1test,y1test))
print('roc_auc_score',roc_auc_score(lopred,y1test))
print(confusion_matrix(lopred,y1test))


train score Logistic regression 0.7155555555555555
test score logistic regression 0.7218934911242604
roc_auc_score 0.7471021303258145
[[47 10]
 [37 75]]


In [462]:
rand.fit(x1train,y1train)

RandomForestClassifier()

In [463]:
randpred = rand.predict(x1test)

In [464]:
print('train score random forest',rand.score(x1train,y1train))
print('test score random forest',rand.score(x1test,y1test))
print('roc_auc_score',roc_auc_score(randpred,y1test))
print(confusion_matrix(randpred,y1test))

train score random forest 1.0
test score random forest 0.8875739644970414
roc_auc_score 0.8881172839506173
[[73  8]
 [11 77]]


In [465]:
tree.fit(x1train,y1train)

DecisionTreeClassifier()

In [466]:
treepred = tree.predict(x1test)

In [467]:
print('train score Desicion tree',tree.score(x1train,y1train))
print('test score Desicion tree',tree.score(x1test,y1test))
print('roc_auc_score',roc_auc_score(treepred,y1test))
print(confusion_matrix(treepred,y1test))

train score Desicion tree 1.0
test score Desicion tree 0.8579881656804734
roc_auc_score 0.8746707638279193
[[81 21]
 [ 3 64]]


In [468]:
ada.fit(x1train,y1train)

AdaBoostClassifier()

In [469]:
adapred = ada.predict(x1test)

In [470]:
print('train score adaboost',ada.score(x1train,y1train))
print('test score adaboost',ada.score(x1test,y1test))
print('roc_auc_score',roc_auc_score(adapred,y1test))
print(confusion_matrix(adapred,y1test))

train score adaboost 0.8474074074074074
test score adaboost 0.6982248520710059
roc_auc_score 0.7045652173913043
[[51 18]
 [33 67]]


In [471]:
grad.fit(x1train,y1train)

GradientBoostingClassifier()

In [472]:
gradpred = grad.predict(x1test)

In [473]:
print('train score gradientboost',grad.score(x1train,y1train))
print('test score gradientboost',grad.score(x1test,y1test))
print('roc_auc_score',roc_auc_score(gradpred,y1test))
print(confusion_matrix(gradpred,y1test))

train score gradientboost 0.9318518518518518
test score gradientboost 0.8165680473372781
roc_auc_score 0.8270289855072464
[[61  8]
 [23 77]]


In [474]:
#hyperpearemeter tuning

In [778]:
model1 = DecisionTreeClassifier(max_depth = 3)

In [779]:
model1.fit(xtrain,ytrain)

DecisionTreeClassifier(max_depth=3)

In [780]:
model1pred = model1.predict(xtest)

In [781]:
print(model1.score(xtrain,ytrain))
print(model1.score(xtest,ytest))
print(roc_auc_score(model1pred,ytest))
print(confusion_matrix(model1pred,ytest))

0.8126272912423625
0.8130081300813008
0.8328082808280829
[[19  3]
 [20 81]]


In [798]:
treemodel1 = DecisionTreeClassifier(max_depth = 5)

In [799]:
treemodel1.fit(x1train,y1train)

DecisionTreeClassifier(max_depth=5)

In [800]:
treemodel1pred = model1.predict(x1test)

In [801]:
print(treemodel1.score(x1train,y1train))
print(treemodel1.score(x1test,y1test))
print(roc_auc_score(treemodel1pred,y1test))
print(confusion_matrix(treemodel1pred,y1test))

0.8237037037037037
0.6982248520710059
0.755920820077766
[[40  6]
 [44 79]]


In [810]:
model2 = RandomForestClassifier(n_estimators= 100,
    criterion='gini',
    max_depth=5)

In [811]:
model2.fit(xtrain,ytrain)

RandomForestClassifier(max_depth=5)

In [812]:
model2pred = model2.predict(xtest)

In [813]:
print(model2.score(xtrain,ytrain))
print(model2.score(xtest,ytest))
print(roc_auc_score(model2pred,ytest))
print(confusion_matrix(model2pred,ytest))

0.8167006109979633
0.8211382113821138
0.8727226720647774
[[18  1]
 [21 83]]


In [712]:
randmodel2 = RandomForestClassifier(n_estimators=250,
    criterion='entropy',
    max_depth=4)

In [713]:
randmodel2.fit(x1train,y1train)

RandomForestClassifier(criterion='entropy', max_depth=4, n_estimators=250)

In [714]:
randmodel2pred = model2.predict(x1test)

In [715]:
print(randmodel2.score(x1train,y1train))
print(randmodel2.score(x1test,y1test))
print(roc_auc_score(randmodel2pred,y1test))
print(confusion_matrix(randmodel2pred,y1test))

0.7807407407407407
0.7455621301775148
0.9001912327155046
[[65  1]
 [19 84]]


In [720]:
#model

#model2 is best model(train score = 82,test score = 82,roc = 87)

# prediction

In [868]:
test = pd.read_csv(r'test_lAUu6dG.csv')

In [870]:
loanid = test['Loan_ID']

In [871]:
test

Loan_ID Gender Married Dependents     Education Self_Employed  \
0    LP001015   Male     Yes          0      Graduate            No   
1    LP001022   Male     Yes          1      Graduate            No   
2    LP001031   Male     Yes          2      Graduate            No   
3    LP001035   Male     Yes          2      Graduate            No   
4    LP001051   Male      No          0  Not Graduate            No   
..        ...    ...     ...        ...           ...           ...   
362  LP002971   Male     Yes         3+  Not Graduate           Yes   
363  LP002975   Male     Yes          0      Graduate            No   
364  LP002980   Male      No          0      Graduate            No   
365  LP002986   Male     Yes          0      Graduate            No   
366  LP002989   Male      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0       110.0             360.0   
1               3076               1500       126.0             360.0   
2               5000               1800       208.0             360.0   
3               2340               2546       100.0             360.0   
4               3276                  0        78.0             360.0   
..               ...                ...         ...               ...   
362             4009               1777       113.0             360.0   
363             4158                709       115.0             360.0   
364             3250               1993       126.0             360.0   
365             5000               2393       158.0             360.0   
366             9200                  0        98.0             180.0   

     Credit_History Property_Area  
0               1.0         Urban  
1               1.0         Urban  
2               1.0         Urban  
3               NaN         Urban  
4               1.0         Urban  
..              ...           ...  
362             1.0         Urban  
363             1.0         Urban  
364             NaN     Semiurban  
365             1.0         Rural  
366             1.0         Rural  

[367 rows x 12 columns]

In [873]:
test['Loan_ID'] = label.fit_transform(test['Loan_ID'])
test['Gender']= label.fit_transform(test['Gender'])
test['Married'] = label.fit_transform(test['Married'])
test['Education'] = label.fit_transform(test['Education'])
test['Self_Employed'] = label.fit_transform(test['Self_Employed'])
test['Property_Area'] = label.fit_transform(test['Property_Area'])

In [874]:
test

Loan_ID  Gender  Married Dependents  Education  Self_Employed  \
0          0       1        1          0          0              0   
1          1       1        1          1          0              0   
2          2       1        1          2          0              0   
3          3       1        1          2          0              0   
4          4       1        0          0          1              0   
..       ...     ...      ...        ...        ...            ...   
362      362       1        1         3+          1              1   
363      363       1        1          0          0              0   
364      364       1        0          0          0              0   
365      365       1        1          0          0              0   
366      366       1        0          0          0              1   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0       110.0             360.0   
1               3076               1500       126.0             360.0   
2               5000               1800       208.0             360.0   
3               2340               2546       100.0             360.0   
4               3276                  0        78.0             360.0   
..               ...                ...         ...               ...   
362             4009               1777       113.0             360.0   
363             4158                709       115.0             360.0   
364             3250               1993       126.0             360.0   
365             5000               2393       158.0             360.0   
366             9200                  0        98.0             180.0   

     Credit_History  Property_Area  
0               1.0              2  
1               1.0              2  
2               1.0              2  
3               NaN              2  
4               1.0              2  
..              ...            ...  
362             1.0              2  
363             1.0              2  
364             NaN              1  
365             1.0              0  
366             1.0              0  

[367 rows x 12 columns]

In [875]:
test.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           10
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

In [876]:
test['Dependents'].mode()

0    0
dtype: object

In [877]:
test['Dependents'] = test['Dependents'].fillna('0')

In [878]:
test['Dependents'].isnull().sum()

0

In [879]:
test['LoanAmount'].mean()

136.13259668508286

In [880]:
test['LoanAmount'] = test['LoanAmount'].fillna(136.0)

In [881]:
test['Loan_Amount_Term'].mean()

342.53739612188366

In [882]:
test['Loan_Amount_Term'] = test['Loan_Amount_Term'].fillna(342.0)

In [883]:
test['Credit_History'].mean()

0.8254437869822485

In [884]:
test['Credit_History'] = test['Credit_History'].fillna(1)

In [885]:
test.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [886]:
test['Dependents'] = label.fit_transform(test['Dependents'])
test['LoanAmount'] = test['LoanAmount'].astype(float)
test['Credit_History'] = test['Credit_History'].astype(float)

In [887]:
test

Loan_ID  Gender  Married  Dependents  Education  Self_Employed  \
0          0       1        1           0          0              0   
1          1       1        1           1          0              0   
2          2       1        1           2          0              0   
3          3       1        1           2          0              0   
4          4       1        0           0          1              0   
..       ...     ...      ...         ...        ...            ...   
362      362       1        1           3          1              1   
363      363       1        1           0          0              0   
364      364       1        0           0          0              0   
365      365       1        1           0          0              0   
366      366       1        0           0          0              1   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0       110.0             360.0   
1               3076               1500       126.0             360.0   
2               5000               1800       208.0             360.0   
3               2340               2546       100.0             360.0   
4               3276                  0        78.0             360.0   
..               ...                ...         ...               ...   
362             4009               1777       113.0             360.0   
363             4158                709       115.0             360.0   
364             3250               1993       126.0             360.0   
365             5000               2393       158.0             360.0   
366             9200                  0        98.0             180.0   

     Credit_History  Property_Area  
0               1.0              2  
1               1.0              2  
2               1.0              2  
3               1.0              2  
4               1.0              2  
..              ...            ...  
362             1.0              2  
363             1.0              2  
364             1.0              1  
365             1.0              0  
366             1.0              0  

[367 rows x 12 columns]

In [918]:
prediction = model2.predict(test)

In [919]:
prediction = pd.DataFrame(prediction)

In [921]:
prediction = prediction.replace(1,'Y')
prediction = prediction.replace(0,'N')

In [923]:
prediction.columns=['Loan_Status']

In [925]:
prediction = pd.concat([loanid,prediction],axis = 1)

In [926]:
prediction

Loan_ID Loan_Status
0    LP001015           Y
1    LP001022           Y
2    LP001031           Y
3    LP001035           Y
4    LP001051           Y
..        ...         ...
362  LP002971           Y
363  LP002975           Y
364  LP002980           Y
365  LP002986           Y
366  LP002989           Y

[367 rows x 2 columns]

In [927]:
prediction.to_csv('loan approvel.csv')